ldap_auth.settings:
  type: mapping
  label: Settings
  mapping:
    miniorange_ldap_customer_admin_email:
      type: 'NULL'
    miniorange_ldap_license_key:
      type: 'NULL'
    miniorange_ldap_customer_id:
      type: string
    miniorange_ldap_customer_admin_token:
      type: string
    miniorange_ldap_customer_api_key:
      type: string
    miniorange_ldap_force_auth:
      type: boolean
    miniorange_ldap_enable_backdoor:
      type: boolean
    miniorange_ldap_default_relaystate:
      type: string
    miniorange_ldap_name:
      type: string
    miniorange_ldap_issuer:
      type: string
    miniorange_ldap_login_url:
      type: string
    miniorange_ldap_logout_url:
      type: string
    miniorange_ldap_x509_certificate:
      type: string
    miniorange_ldap_response_signed:
      type: boolean
    miniorange_ldap_assertion_signed:
      type: boolean
    miniorange_ldap_enable_login:
      type: boolean
    miniorange_ldap_username_attribute:
      type: string
    miniorange_ldap_email_attribute:
      type: string
    miniorange_ldap_attr1_name:
      type: string
    miniorange_ldap_attr5_name:
      type: string
    miniorange_ldap_attr2_name:
      type: string
    miniorange_ldap_attr3_name:
      type: string
    miniorange_ldap_attr4_name:
      type: string
    miniorange_ldap_disable_autocreate_users:
      type: boolean
    miniorange_ldap_default_role:
      type: string
    miniorange_ldap_role1_name:
      type: string
    miniorange_ldap_role2_name:
      type: string
    miniorange_ldap_role3_name:
      type: string
    miniorange_ldap_role4_name:
      type: string
    miniorange_ldap_status:
      type: string
    miniorange_ldap_customer_admin_phone:
      type: 'NULL'
    miniorange_ldap_tx_id:
      type: 'NULL'
    miniorange_ldap_customer_admin_password:
      type: string
    miniorange_ldap_base_url :
      type: string