preset_accent_color: green
preset_focus_color: gin
enable_darkmode: false
classic_toolbar: vertical
icon_default: false
icon_path: 'public://4f011c6_0.png'
high_contrast_mode: false
third_party_settings:
  shortcut:
    module_link: true
_core:
  default_config_hash: CEHTCpo0zzrZOJNa9_M2R_HdYKrq3v1zlRVCf66hh7U
langcode: fr
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
favicon:
  use_default: true
accent_color: ''
focus_color: ''
icon_upload: ''
