third_party_settings:
  shortcut:
    module_link: true
features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://4f011c6.png'
favicon:
  use_default: true
mobile_menu_all_widths: 1
site_branding_bg_color: gray
_core:
  default_config_hash: c5kVSCNYXyJ7W0sRejtsXfs_pSQdS1OMzYMS1y2dLx8
langcode: fr
