features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://logo_sas_basket.png'
favicon:
  use_default: false
  path: 'public://favicon.ico'
  mimetype: image/vnd.microsoft.icon
general:
  wrap_content_in_container: true
  teaser_title_size: default
hero:
  color: primary
forms:
  input_size: ''
  label_size: ''
  input_rounded: false
table:
  bordered: false
  striped: false
  narrow: false
  hoverable: false
  fullwidth: false
typography:
  content_font_family: primary
